### ISSUE TITLE
No train carriages can be bought when using this mod

### ISSUE THREAD

**Issue by Ultroman** [2TallTyler/danish_trains#3]
As much as I love this mod, it stops you from buying cargo wagons, so it currently just breaks the game. Is it not possible to make it just use the wagons from the base set? Or adding the new locomotives without replacing all the existing ones?

**Comment by 2TallTyler** [comment]
My suggestion would be to use another train set. It's drawn to the same scale as RUKTS for freight wagons, or if you want vanilla trains you can use OpenGFX+ Trains.
